import type { Colors } from '../../types';

export const TailwindColors: Colors[] = [
	'red',
	'orange',
	'amber',
	'yellow',
	'lime',
	'green',
	'emerald',
	'teal',
	'cyan',
	'sky',
	'blue',
	'indigo',
	'violet',
	'purple',
	'fuchsia',
	'pink',
	'rose',
	'slate',
	'gray',
	'zinc',
	'neutral',
	'stone',
	'black',
	'white',
];

export const TailwindBGs500 = {
	red: 'bg-red-500',
	orange: 'bg-orange-500',
	amber: 'bg-amber-500',
	yellow: 'bg-yellow-500',
	lime: 'bg-lime-500',
	green: 'bg-green-500',
	emerald: 'bg-emerald-500',
	teal: 'bg-teal-500',
	cyan: 'bg-cyan-500',
	sky: 'bg-sky-500',
	blue: 'bg-blue-500',
	indigo: 'bg-indigo-500',
	violet: 'bg-violet-500',
	purple: 'bg-purple-500',
	fuchsia: 'bg-fuchsia-500',
	pink: 'bg-pink-500',
	rose: 'bg-rose-500',
	slate: 'bg-slate-500',
	gray: 'bg-gray-500',
	zinc: 'bg-zinc-500',
	neutral: 'bg-neutral-500',
	stone: 'bg-stone-500',
	white: 'bg-white',
	black: 'bg-black',
} as Record<Colors, string>;

export const TailwindBGs300 = {
	red: 'bg-red-300',
	orange: 'bg-orange-300',
	amber: 'bg-amber-300',
	yellow: 'bg-yellow-300',
	lime: 'bg-lime-300',
	green: 'bg-green-300',
	emerald: 'bg-emerald-300',
	teal: 'bg-teal-300',
	cyan: 'bg-cyan-300',
	sky: 'bg-sky-300',
	blue: 'bg-blue-300',
	indigo: 'bg-indigo-300',
	violet: 'bg-violet-300',
	purple: 'bg-purple-300',
	fuchsia: 'bg-fuchsia-300',
	pink: 'bg-pink-300',
	rose: 'bg-rose-300',
	slate: 'bg-slate-300',
	gray: 'bg-gray-300',
	zinc: 'bg-zinc-300',
	neutral: 'bg-neutral-300',
	stone: 'bg-stone-300',
	white: 'bg-white',
	black: 'bg-black',
} as Record<Colors, string>;

export const TailwindOutlineColors = {
	red: 'outline-red-600',
	orange: 'outline-orange-600',
	amber: 'outline-amber-600',
	yellow: 'outline-yellow-600',
	lime: 'outline-lime-600',
	green: 'outline-green-600',
	emerald: 'outline-emerald-600',
	teal: 'outline-teal-600',
	cyan: 'outline-cyan-600',
	sky: 'outline-sky-600',
	blue: 'outline-blue-600',
	indigo: 'outline-indigo-600',
	violet: 'outline-violet-600',
	purple: 'outline-purple-600',
	fuchsia: 'outline-fuchsia-600',
	pink: 'outline-pink-600',
	rose: 'outline-rose-600',
	slate: 'outline-slate-600',
	gray: 'outline-gray-600',
	zinc: 'outline-zinc-600',
	neutral: 'outline-neutral-600',
	stone: 'outline-stone-600',
	black: 'outline-black',
	white: 'outline-white',
} as Record<Colors, string>;

export const TailwindDropShadows = {
	red: 'drop-shadow-lg drop-shadow-red-500/30',
	orange: 'drop-shadow-lg drop-shadow-orange-500/30',
	amber: 'drop-shadow-lg drop-shadow-amber-500/30',
	yellow: 'drop-shadow-lg drop-shadow-yellow-500/30',
	lime: 'drop-shadow-lg drop-shadow-lime-500/30',
	green: 'drop-shadow-lg drop-shadow-green-500/30',
	emerald: 'drop-shadow-lg drop-shadow-emerald-500/30',
	teal: 'drop-shadow-lg drop-shadow-teal-500/30',
	cyan: 'drop-shadow-lg drop-shadow-cyan-500/30',
	sky: 'drop-shadow-lg drop-shadow-sky-500/30',
	blue: 'drop-shadow-lg drop-shadow-blue-500/30',
	indigo: 'drop-shadow-lg drop-shadow-indigo-500/30',
	violet: 'drop-shadow-lg drop-shadow-violet-500/30',
	purple: 'drop-shadow-lg drop-shadow-purple-500/30',
	fuchsia: 'drop-shadow-lg drop-shadow-fuchsia-500/30',
	pink: 'drop-shadow-lg drop-shadow-pink-500/30',
	rose: 'drop-shadow-lg drop-shadow-rose-500/30',
	slate: 'drop-shadow-lg drop-shadow-slate-500/30',
	gray: 'drop-shadow-lg drop-shadow-gray-500/30',
	zinc: 'drop-shadow-lg drop-shadow-zinc-500/30',
	neutral: 'drop-shadow-lg drop-shadow-neutral-500/30',
	stone: 'drop-shadow-lg drop-shadow-stone-500/30',
	black: 'drop-shadow-lg drop-shadow-black/30',
	white: 'drop-shadow-lg drop-shadow-white/30',
} as Record<Colors, string>;

export const TailwindFocusBGs500 = {
	red: 'data-focus:bg-red-500 ',
	orange: 'data-focus:bg-orange-500 ',
	amber: 'data-focus:bg-amber-500 ',
	yellow: 'data-focus:bg-yellow-500 ',
	lime: 'data-focus:bg-lime-500 ',
	green: 'data-focus:bg-green-500 ',
	emerald: 'data-focus:bg-emerald-500 ',
	teal: 'data-focus:bg-teal-500 ',
	cyan: 'data-focus:bg-cyan-500 ',
	sky: 'data-focus:bg-sky-500 ',
	blue: 'data-focus:bg-blue-500 ',
	indigo: 'data-focus:bg-indigo-500 ',
	violet: 'data-focus:bg-violet-500 ',
	purple: 'data-focus:bg-purple-500 ',
	fuchsia: 'data-focus:bg-fuchsia-500 ',
	pink: 'data-focus:bg-pink-500 ',
	rose: 'data-focus:bg-rose-500 ',
	slate: 'data-focus:bg-slate-500 ',
	gray: 'data-focus:bg-gray-500 ',
	zinc: 'data-focus:bg-zinc-500 ',
	neutral: 'data-focus:bg-neutral-500 ',
	stone: 'data-focus:bg-stone-500 ',
	black: 'data-focus:bg-black',
	white: 'data-focus:bg-white',
} as Record<Colors, string>;

export const TailwindFocusOutlineColors = {
	red: 'focus:outline-red-600',
	orange: 'focus:outline-orange-600',
	amber: 'focus:outline-amber-600',
	yellow: 'focus:outline-yellow-600',
	lime: 'focus:outline-lime-600',
	green: 'focus:outline-green-600',
	emerald: 'focus:outline-emerald-600',
	teal: 'focus:outline-teal-600',
	cyan: 'focus:outline-cyan-600',
	sky: 'focus:outline-sky-600',
	blue: 'focus:outline-blue-600',
	indigo: 'focus:outline-indigo-600',
	violet: 'focus:outline-violet-600',
	purple: 'focus:outline-purple-600',
	fuchsia: 'focus:outline-fuchsia-600',
	pink: 'focus:outline-pink-600',
	rose: 'focus:outline-rose-600',
	slate: 'focus:outline-slate-600',
	gray: 'focus:outline-gray-600',
	zinc: 'focus:outline-zinc-600',
	neutral: 'focus:outline-neutral-600',
	stone: 'focus:outline-stone-600',
	black: 'focus:outline-black',
	white: 'focus:outline-white',
} as Record<Colors, string>;

export const TailwindCheckedBGs500 = {
	red: 'has-checked:bg-red-500',
	orange: 'has-checked:bg-orange-500',
	amber: 'has-checked:bg-amber-500',
	yellow: 'has-checked:bg-yellow-500',
	lime: 'has-checked:bg-lime-500',
	green: 'has-checked:bg-green-500',
	emerald: 'has-checked:bg-emerald-500',
	teal: 'has-checked:bg-teal-500',
	cyan: 'has-checked:bg-cyan-500',
	sky: 'has-checked:bg-sky-500',
	blue: 'has-checked:bg-blue-500',
	indigo: 'has-checked:bg-indigo-500',
	violet: 'has-checked:bg-violet-500',
	purple: 'has-checked:bg-purple-500',
	fuchsia: 'has-checked:bg-fuchsia-500',
	pink: 'has-checked:bg-pink-500',
	rose: 'has-checked:bg-rose-500',
	slate: 'has-checked:bg-slate-500',
	gray: 'has-checked:bg-gray-500',
	zinc: 'has-checked:bg-zinc-500',
	neutral: 'has-checked:bg-neutral-500',
	stone: 'has-checked:bg-stone-500',
	white: 'has-checked:bg-white',
	black: 'has-checked:bg-black',
} as Record<Colors, string>;

export const TailwindTextColors500 = {
	red: 'text-red-500 ',
	orange: 'text-orange-500 ',
	amber: 'text-amber-500 ',
	yellow: 'text-yellow-500 ',
	lime: 'text-lime-500 ',
	green: 'text-green-500 ',
	emerald: 'text-emerald-500 ',
	teal: 'text-teal-500 ',
	cyan: 'text-cyan-500 ',
	sky: 'text-sky-500 ',
	blue: 'text-blue-500 ',
	indigo: 'text-indigo-500 ',
	violet: 'text-violet-500 ',
	purple: 'text-purple-500 ',
	fuchsia: 'text-fuchsia-500 ',
	pink: 'text-pink-500 ',
	rose: 'text-rose-500 ',
	slate: 'text-slate-500 ',
	gray: 'text-gray-500 ',
	zinc: 'text-zinc-500 ',
	neutral: 'text-neutral-500 ',
	stone: 'text-stone-500 ',
	white: 'text-white',
	black: 'text-black',
} as Record<Colors, string>;

export const TailwindDivideColors = {
	red: 'divide-red-700',
	orange: 'divide-orange-700',
	amber: 'divide-amber-700',
	yellow: 'divide-yellow-700',
	lime: 'divide-lime-700',
	green: 'divide-green-700',
	emerald: 'divide-emerald-700',
	teal: 'divide-teal-700',
	cyan: 'divide-cyan-700',
	sky: 'divide-sky-700',
	blue: 'divide-blue-700',
	indigo: 'divide-indigo-700',
	violet: 'divide-violet-700',
	purple: 'divide-purple-700',
	fuchsia: 'divide-fuchsia-700',
	pink: 'divide-pink-700',
	rose: 'divide-rose-700',
	slate: 'divide-slate-700',
	gray: 'divide-gray-700',
	zinc: 'divide-zinc-700',
	neutral: 'divide-neutral-700',
	stone: 'divide-stone-700',
	white: 'divide-white',
	black: 'divide-black',
} as Record<Colors, string>;

export const TailwindHoverBGs700 = {
	red: 'hover:bg-red-700',
	orange: 'hover:bg-orange-700',
	amber: 'hover:bg-amber-700',
	yellow: 'hover:bg-yellow-700',
	lime: 'hover:bg-lime-700',
	green: 'hover:bg-green-700',
	emerald: 'hover:bg-emerald-700',
	teal: 'hover:bg-teal-700',
	cyan: 'hover:bg-cyan-700',
	sky: 'hover:bg-sky-700',
	blue: 'hover:bg-blue-700',
	indigo: 'hover:bg-indigo-700',
	violet: 'hover:bg-violet-700',
	purple: 'hover:bg-purple-700',
	fuchsia: 'hover:bg-fuchsia-700',
	pink: 'hover:bg-pink-700',
	rose: 'hover:bg-rose-700',
	slate: 'hover:bg-slate-700',
	gray: 'hover:bg-gray-700',
	zinc: 'hover:bg-zinc-700',
	neutral: 'hover:bg-neutral-700',
	stone: 'hover:bg-stone-700',
	white: 'hover:bg-white',
	black: 'hover:bg-black',
} as Record<Colors, string>;

export const TailwindFocusVisibleOutlineColors = {
	red: 'focus-visible:outline-red-400',
	orange: 'focus-visible:outline-orange-400',
	amber: 'focus-visible:outline-amber-400',
	yellow: 'focus-visible:outline-yellow-400',
	lime: 'focus-visible:outline-lime-400',
	green: 'focus-visible:outline-green-400',
	emerald: 'focus-visible:outline-emerald-400',
	teal: 'focus-visible:outline-teal-400',
	cyan: 'focus-visible:outline-cyan-400',
	sky: 'focus-visible:outline-sky-400',
	blue: 'focus-visible:outline-blue-400',
	indigo: 'focus-visible:outline-indigo-400',
	violet: 'focus-visible:outline-violet-400',
	purple: 'focus-visible:outline-purple-400',
	fuchsia: 'focus-visible:outline-fuchsia-400',
	pink: 'focus-visible:outline-pink-400',
	rose: 'focus-visible:outline-rose-400',
	slate: 'focus-visible:outline-slate-400',
	gray: 'focus-visible:outline-gray-400',
	zinc: 'focus-visible:outline-zinc-400',
	neutral: 'focus-visible:outline-neutral-400',
	stone: 'focus-visible:outline-stone-400',
	black: 'focus-visible:outline-black',
	white: 'focus-visible:outline-white',
} as Record<Colors, string>;

export const TailwindGroupDataFocusTextColors200 = {
	red: 'group-data-focus:text-red-200',
	orange:
		'group-data-focus:text-orange-200',
	amber: 'group-data-focus:text-amber-200',
	yellow:
		'group-data-focus:text-yellow-200',
	lime: 'group-data-focus:text-lime-200',
	green: 'group-data-focus:text-green-200',
	emerald:
		'group-data-focus:text-emerald-200',
	teal: 'group-data-focus:text-teal-200',
	cyan: 'group-data-focus:text-cyan-200',
	sky: 'group-data-focus:text-sky-200',
	blue: 'group-data-focus:text-blue-200',
	indigo:
		'group-data-focus:text-indigo-200',
	violet:
		'group-data-focus:text-violet-200',
	purple:
		'group-data-focus:text-purple-200',
	fuchsia:
		'group-data-focus:text-fuchsia-200',
	pink: 'group-data-focus:text-pink-200',
	rose: 'group-data-focus:text-rose-200',
	slate: 'group-data-focus:text-slate-200',
	gray: 'group-data-focus:text-gray-200',
	zinc: 'group-data-focus:text-zinc-200',
	neutral:
		'group-data-focus:text-neutral-200',
	stone: 'group-data-focus:text-stone-200',
	white: 'group-data-focus:text-white',
	black: 'group-data-focus:text-black',
} as Record<Colors, string>;

export const TailwindCanvasColorHexMap = {
	red: '#ff6467',
	orange: '#ffb86a',
	amber: '#ffd230',
	yellow: '#ffdf20',
	lime: '#9ae600',
	green: '#05df72',
	emerald: '#00d492',
	teal: '#46ecd5',
	cyan: '#00d3f2',
	sky: '#00bcff',
	blue: '#51a2ff',
	indigo: '#7c86ff',
	violet: '#a684ff',
	purple: '#c27aff',
	fuchsia: '#ed6bff',
	pink: '#fda5d5',
	rose: '#ffa1ad',
	slate: '#90a1b9',
	gray: '#99a1af',
	zinc: '#9f9fa9',
	neutral: '#a1a1a1',
	stone: '#a6a09b',
	black: '#09090b',
	white: '#e7e5e4',
} as Record<Colors, string>;
