import type { Colors } from '../../types';

export const TailwindColors: Colors[] = [
	'red',
	'orange',
	'amber',
	'yellow',
	'lime',
	'green',
	'emerald',
	'teal',
	'cyan',
	'sky',
	'blue',
	'indigo',
	'violet',
	'purple',
	'fuchsia',
	'pink',
	'rose',
	'slate',
	'gray',
	'zinc',
	'neutral',
	'stone',
	'black',
	'white',
];

export const TailwindBGs500 = {
	red: 'bg-red-500',
	orange: 'bg-orange-500',
	amber: 'bg-amber-500',
	yellow: 'bg-yellow-500',
	lime: 'bg-lime-500',
	green: 'bg-green-500',
	emerald: 'bg-emerald-500',
	teal: 'bg-teal-500',
	cyan: 'bg-cyan-500',
	sky: 'bg-sky-500',
	blue: 'bg-blue-500',
	indigo: 'bg-indigo-500',
	violet: 'bg-violet-500',
	purple: 'bg-purple-500',
	fuchsia: 'bg-fuchsia-500',
	pink: 'bg-pink-500',
	rose: 'bg-rose-500',
	slate: 'bg-slate-500',
	gray: 'bg-gray-500',
	zinc: 'bg-zinc-500',
	neutral: 'bg-neutral-500',
	stone: 'bg-stone-500',
	white: 'bg-white',
	black: 'bg-black',
} as Record<Colors, string>;

export const TailwindBGs300 = {
	red: 'bg-red-300',
	orange: 'bg-orange-300',
	amber: 'bg-amber-300',
	yellow: 'bg-yellow-300',
	lime: 'bg-lime-300',
	green: 'bg-green-300',
	emerald: 'bg-emerald-300',
	teal: 'bg-teal-300',
	cyan: 'bg-cyan-300',
	sky: 'bg-sky-300',
	blue: 'bg-blue-300',
	indigo: 'bg-indigo-300',
	violet: 'bg-violet-300',
	purple: 'bg-purple-300',
	fuchsia: 'bg-fuchsia-300',
	pink: 'bg-pink-300',
	rose: 'bg-rose-300',
	slate: 'bg-slate-300',
	gray: 'bg-gray-300',
	zinc: 'bg-zinc-300',
	neutral: 'bg-neutral-300',
	stone: 'bg-stone-300',
	white: 'bg-white',
	black: 'bg-black',
} as Record<Colors, string>;

export const TailwindOutlineColors = {
	red: 'outline-red-600',
	orange: 'outline-orange-600',
	amber: 'outline-amber-600',
	yellow: 'outline-yellow-600',
	lime: 'outline-lime-600',
	green: 'outline-green-600',
	emerald: 'outline-emerald-600',
	teal: 'outline-teal-600',
	cyan: 'outline-cyan-600',
	sky: 'outline-sky-600',
	blue: 'outline-blue-600',
	indigo: 'outline-indigo-600',
	violet: 'outline-violet-600',
	purple: 'outline-purple-600',
	fuchsia: 'outline-fuchsia-600',
	pink: 'outline-pink-600',
	rose: 'outline-rose-600',
	slate: 'outline-slate-600',
	gray: 'outline-gray-600',
	zinc: 'outline-zinc-600',
	neutral: 'outline-neutral-600',
	stone: 'outline-stone-600',
	black: 'outline-black',
	white: 'outline-white',
} as Record<Colors, string>;

export const TailwindDropShadows = {
	red: 'drop-shadow-lg drop-shadow-red-500/30',
	orange: 'drop-shadow-lg drop-shadow-orange-500/30',
	amber: 'drop-shadow-lg drop-shadow-amber-500/30',
	yellow: 'drop-shadow-lg drop-shadow-yellow-500/30',
	lime: 'drop-shadow-lg drop-shadow-lime-500/30',
	green: 'drop-shadow-lg drop-shadow-green-500/30',
	emerald: 'drop-shadow-lg drop-shadow-emerald-500/30',
	teal: 'drop-shadow-lg drop-shadow-teal-500/30',
	cyan: 'drop-shadow-lg drop-shadow-cyan-500/30',
	sky: 'drop-shadow-lg drop-shadow-sky-500/30',
	blue: 'drop-shadow-lg drop-shadow-blue-500/30',
	indigo: 'drop-shadow-lg drop-shadow-indigo-500/30',
	violet: 'drop-shadow-lg drop-shadow-violet-500/30',
	purple: 'drop-shadow-lg drop-shadow-purple-500/30',
	fuchsia: 'drop-shadow-lg drop-shadow-fuchsia-500/30',
	pink: 'drop-shadow-lg drop-shadow-pink-500/30',
	rose: 'drop-shadow-lg drop-shadow-rose-500/30',
	slate: 'drop-shadow-lg drop-shadow-slate-500/30',
	gray: 'drop-shadow-lg drop-shadow-gray-500/30',
	zinc: 'drop-shadow-lg drop-shadow-zinc-500/30',
	neutral: 'drop-shadow-lg drop-shadow-neutral-500/30',
	stone: 'drop-shadow-lg drop-shadow-stone-500/30',
	black: 'drop-shadow-lg drop-shadow-black/30',
	white: 'drop-shadow-lg drop-shadow-white/30',
} as Record<Colors, string>;
