import type { Colors } from '../../types';

export const TailwindColors: Colors[] = [
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
  'slate',
  'gray',
  'zinc',
  'neutral',
  'stone',
  'black',
  'white',
];

export const TailwindBGs500 = {
  red: 'bg-red-500',
  orange: 'bg-orange-500',
  amber: 'bg-amber-500',
  yellow: 'bg-yellow-500',
  lime: 'bg-lime-500',
  green: 'bg-green-500',
  emerald: 'bg-emerald-500',
  teal: 'bg-teal-500',
  cyan: 'bg-cyan-500',
  sky: 'bg-sky-500',
  blue: 'bg-blue-500',
  indigo: 'bg-indigo-500',
  violet: 'bg-violet-500',
  purple: 'bg-purple-500',
  fuchsia: 'bg-fuchsia-500',
  pink: 'bg-pink-500',
  rose: 'bg-rose-500',
  slate: 'bg-slate-500',
  gray: 'bg-gray-500',
  zinc: 'bg-zinc-500',
  neutral: 'bg-neutral-500',
  stone: 'bg-stone-500',
  white: 'bg-white',
  black: 'bg-black',
} as Record<Colors, string>;

export const TailwindBGs300 = {
  red: 'bg-red-300',
  orange: 'bg-orange-300',
  amber: 'bg-amber-300',
  yellow: 'bg-yellow-300',
  lime: 'bg-lime-300',
  green: 'bg-green-300',
  emerald: 'bg-emerald-300',
  teal: 'bg-teal-300',
  cyan: 'bg-cyan-300',
  sky: 'bg-sky-300',
  blue: 'bg-blue-300',
  indigo: 'bg-indigo-300',
  violet: 'bg-violet-300',
  purple: 'bg-purple-300',
  fuchsia: 'bg-fuchsia-300',
  pink: 'bg-pink-300',
  rose: 'bg-rose-300',
  slate: 'bg-slate-300',
  gray: 'bg-gray-300',
  zinc: 'bg-zinc-300',
  neutral: 'bg-neutral-300',
  stone: 'bg-stone-300',
  white: 'bg-white',
  black: 'bg-black',
} as Record<Colors, string>;

export const TailwindOutlineColors = {
  red: 'outline-red-600',
  orange: 'outline-orange-600',
  amber: 'outline-amber-600',
  yellow: 'outline-yellow-600',
  lime: 'outline-lime-600',
  green: 'outline-green-600',
  emerald: 'outline-emerald-600',
  teal: 'outline-teal-600',
  cyan: 'outline-cyan-600',
  sky: 'outline-sky-600',
  blue: 'outline-blue-600',
  indigo: 'outline-indigo-600',
  violet: 'outline-violet-600',
  purple: 'outline-purple-600',
  fuchsia: 'outline-fuchsia-600',
  pink: 'outline-pink-600',
  rose: 'outline-rose-600',
  slate: 'outline-slate-600',
  gray: 'outline-gray-600',
  zinc: 'outline-zinc-600',
  neutral: 'outline-neutral-600',
  stone: 'outline-stone-600',
  black: 'outline-black',
  white: 'outline-white',
} as Record<Colors, string>;

export const TailwindDropShadows = {
  red: 'drop-shadow-lg drop-shadow-red-500/30',
  orange: 'drop-shadow-lg drop-shadow-orange-500/30',
  amber: 'drop-shadow-lg drop-shadow-amber-500/30',
  yellow: 'drop-shadow-lg drop-shadow-yellow-500/30',
  lime: 'drop-shadow-lg drop-shadow-lime-500/30',
  green: 'drop-shadow-lg drop-shadow-green-500/30',
  emerald: 'drop-shadow-lg drop-shadow-emerald-500/30',
  teal: 'drop-shadow-lg drop-shadow-teal-500/30',
  cyan: 'drop-shadow-lg drop-shadow-cyan-500/30',
  sky: 'drop-shadow-lg drop-shadow-sky-500/30',
  blue: 'drop-shadow-lg drop-shadow-blue-500/30',
  indigo: 'drop-shadow-lg drop-shadow-indigo-500/30',
  violet: 'drop-shadow-lg drop-shadow-violet-500/30',
  purple: 'drop-shadow-lg drop-shadow-purple-500/30',
  fuchsia: 'drop-shadow-lg drop-shadow-fuchsia-500/30',
  pink: 'drop-shadow-lg drop-shadow-pink-500/30',
  rose: 'drop-shadow-lg drop-shadow-rose-500/30',
  slate: 'drop-shadow-lg drop-shadow-slate-500/30',
  gray: 'drop-shadow-lg drop-shadow-gray-500/30',
  zinc: 'drop-shadow-lg drop-shadow-zinc-500/30',
  neutral: 'drop-shadow-lg drop-shadow-neutral-500/30',
  stone: 'drop-shadow-lg drop-shadow-stone-500/30',
  black: 'drop-shadow-lg drop-shadow-black/30',
  white: 'drop-shadow-lg drop-shadow-white/30',
} as Record<Colors, string>;

export const TailwindFocusBGs500 = {
  red: 'data-focus:bg-red-500 dark:data-focus:bg-red-500',
  orange: 'data-focus:bg-orange-500 dark:data-focus:bg-orange-500',
  amber: 'data-focus:bg-amber-500 dark:data-focus:bg-amber-500',
  yellow: 'data-focus:bg-yellow-500 dark:data-focus:bg-yellow-500',
  lime: 'data-focus:bg-lime-500 dark:data-focus:bg-lime-500',
  green: 'data-focus:bg-green-500 dark:data-focus:bg-green-500',
  emerald: 'data-focus:bg-emerald-500 dark:data-focus:bg-emerald-500',
  teal: 'data-focus:bg-teal-500 dark:data-focus:bg-teal-500',
  cyan: 'data-focus:bg-cyan-500 dark:data-focus:bg-cyan-500',
  sky: 'data-focus:bg-sky-500 dark:data-focus:bg-sky-500',
  blue: 'data-focus:bg-blue-500 dark:data-focus:bg-blue-500',
  indigo: 'data-focus:bg-indigo-500 dark:data-focus:bg-indigo-500',
  violet: 'data-focus:bg-violet-500 dark:data-focus:bg-violet-500',
  purple: 'data-focus:bg-purple-500 dark:data-focus:bg-purple-500',
  fuchsia: 'data-focus:bg-fuchsia-500 dark:data-focus:bg-fuchsia-500',
  pink: 'data-focus:bg-pink-500 dark:data-focus:bg-pink-500',
  rose: 'data-focus:bg-rose-500 dark:data-focus:bg-rose-500',
  slate: 'data-focus:bg-slate-500 dark:data-focus:bg-slate-500',
  gray: 'data-focus:bg-gray-500 dark:data-focus:bg-gray-500',
  zinc: 'data-focus:bg-zinc-500 dark:data-focus:bg-zinc-500',
  neutral: 'data-focus:bg-neutral-500 dark:data-focus:bg-neutral-500',
  stone: 'data-focus:bg-stone-500 dark:data-focus:bg-stone-500',
  black: 'data-focus:bg-black dark:data-focus:bg-black',
  white: 'data-focus:bg-white dark:data-focus:bg-white',
} as Record<Colors, string>;

export const TailwindFocusOutlineColors = {
  red: 'focus:outline-red-600 dark:focus:outline-red-600',
  orange: 'focus:outline-orange-600 dark:focus:outline-orange-600',
  amber: 'focus:outline-amber-600 dark:focus:outline-amber-600',
  yellow: 'focus:outline-yellow-600 dark:focus:outline-yellow-600',
  lime: 'focus:outline-lime-600 dark:focus:outline-lime-600',
  green: 'focus:outline-green-600 dark:focus:outline-green-600',
  emerald: 'focus:outline-emerald-600 dark:focus:outline-emerald-600',
  teal: 'focus:outline-teal-600 dark:focus:outline-teal-600',
  cyan: 'focus:outline-cyan-600 dark:focus:outline-cyan-600',
  sky: 'focus:outline-sky-600 dark:focus:outline-sky-600',
  blue: 'focus:outline-blue-600 dark:focus:outline-blue-600',
  indigo: 'focus:outline-indigo-600 dark:focus:outline-indigo-600',
  violet: 'focus:outline-violet-600 dark:focus:outline-violet-600',
  purple: 'focus:outline-purple-600 dark:focus:outline-purple-600',
  fuchsia: 'focus:outline-fuchsia-600 dark:focus:outline-fuchsia-600',
  pink: 'focus:outline-pink-600 dark:focus:outline-pink-600',
  rose: 'focus:outline-rose-600 dark:focus:outline-rose-600',
  slate: 'focus:outline-slate-600 dark:focus:outline-slate-600',
  gray: 'focus:outline-gray-600 dark:focus:outline-gray-600',
  zinc: 'focus:outline-zinc-600 dark:focus:outline-zinc-600',
  neutral: 'focus:outline-neutral-600 dark:focus:outline-neutral-600',
  stone: 'focus:outline-stone-600 dark:focus:outline-stone-600',
  black: 'focus:outline-black dark:focus:outline-black',
  white: 'focus:outline-white dark:focus:outline-white',
} as Record<Colors, string>;

export const TailwindCheckedBGs500 = {
  red: 'has-checked:bg-red-500 dark:has-checked:bg-red-500',
  orange: 'has-checked:bg-orange-500 dark:has-checked:bg-orange-500',
  amber: 'has-checked:bg-amber-500 dark:has-checked:bg-amber-500',
  yellow: 'has-checked:bg-yellow-500 dark:has-checked:bg-yellow-500',
  lime: 'has-checked:bg-lime-500 dark:has-checked:bg-lime-500',
  green: 'has-checked:bg-green-500 dark:has-checked:bg-green-500',
  emerald: 'has-checked:bg-emerald-500 dark:has-checked:bg-emerald-500',
  teal: 'has-checked:bg-teal-500 dark:has-checked:bg-teal-500',
  cyan: 'has-checked:bg-cyan-500 dark:has-checked:bg-cyan-500',
  sky: 'has-checked:bg-sky-500 dark:has-checked:bg-sky-500',
  blue: 'has-checked:bg-blue-500 dark:has-checked:bg-blue-500',
  indigo: 'has-checked:bg-indigo-500 dark:has-checked:bg-indigo-500',
  violet: 'has-checked:bg-violet-500 dark:has-checked:bg-violet-500',
  purple: 'has-checked:bg-purple-500 dark:has-checked:bg-purple-500',
  fuchsia: 'has-checked:bg-fuchsia-500 dark:has-checked:bg-fuchsia-500',
  pink: 'has-checked:bg-pink-500 dark:has-checked:bg-pink-500',
  rose: 'has-checked:bg-rose-500 dark:has-checked:bg-rose-500',
  slate: 'has-checked:bg-slate-500 dark:has-checked:bg-slate-500',
  gray: 'has-checked:bg-gray-500 dark:has-checked:bg-gray-500',
  zinc: 'has-checked:bg-zinc-500 dark:has-checked:bg-zinc-500',
  neutral: 'has-checked:bg-neutral-500 dark:has-checked:bg-neutral-500',
  stone: 'has-checked:bg-stone-500 dark:has-checked:bg-stone-500',
  white: 'has-checked:bg-white dark:has-checked:bg-white',
  black: 'has-checked:bg-black dark:has-checked:bg-black',
} as Record<Colors, string>;

export const TailwindTextColors500 = {
  red: 'text-red-500 ',
  orange: 'text-orange-500 ',
  amber: 'text-amber-500 ',
  yellow: 'text-yellow-500 ',
  lime: 'text-lime-500 ',
  green: 'text-green-500 ',
  emerald: 'text-emerald-500 ',
  teal: 'text-teal-500 ',
  cyan: 'text-cyan-500 ',
  sky: 'text-sky-500 ',
  blue: 'text-blue-500 ',
  indigo: 'text-indigo-500 ',
  violet: 'text-violet-500 ',
  purple: 'text-purple-500 ',
  fuchsia: 'text-fuchsia-500 ',
  pink: 'text-pink-500 ',
  rose: 'text-rose-500 ',
  slate: 'text-slate-500 ',
  gray: 'text-gray-500 ',
  zinc: 'text-zinc-500 ',
  neutral: 'text-neutral-500 ',
  stone: 'text-stone-500 ',
  white: 'text-white',
  black: 'text-black',
} as Record<Colors, string>

export const TailwindDivideColors = {
  red: 'divide-red-700 dark:divide-red-600',
  orange: 'divide-orange-700 dark:divide-orange-600',
  amber: 'divide-amber-700 dark:divide-amber-600',
  yellow: 'divide-yellow-700 dark:divide-yellow-600',
  lime: 'divide-lime-700 dark:divide-lime-600',
  green: 'divide-green-700 dark:divide-green-600',
  emerald: 'divide-emerald-700 dark:divide-emerald-600',
  teal: 'divide-teal-700 dark:divide-teal-600',
  cyan: 'divide-cyan-700 dark:divide-cyan-600',
  sky: 'divide-sky-700 dark:divide-sky-600',
  blue: 'divide-blue-700 dark:divide-blue-600',
  indigo: 'divide-indigo-700 dark:divide-indigo-600',
  violet: 'divide-violet-700 dark:divide-violet-600',
  purple: 'divide-purple-700 dark:divide-purple-600',
  fuchsia: 'divide-fuchsia-700 dark:divide-fuchsia-600',
  pink: 'divide-pink-700 dark:divide-pink-600',
  rose: 'divide-rose-700 dark:divide-rose-600',
  slate: 'divide-slate-700 dark:divide-slate-600',
  gray: 'divide-gray-700 dark:divide-gray-600',
  zinc: 'divide-zinc-700 dark:divide-zinc-600',
  neutral: 'divide-neutral-700 dark:divide-neutral-600',
  stone: 'divide-stone-700 dark:divide-stone-600',
  white: 'divide-white dark:divide-white',
  black: 'divide-black dark:divide-black',
} as Record<Colors, string>


export const TailwindHoverBGs700 = {
  red: 'hover:bg-red-700 dark:hover:bg-red-400',
  orange: 'hover:bg-orange-700 dark:hover:bg-orange-400',
  amber: 'hover:bg-amber-700 dark:hover:bg-amber-400',
  yellow: 'hover:bg-yellow-700 dark:hover:bg-yellow-400',
  lime: 'hover:bg-lime-700 dark:hover:bg-lime-400',
  green: 'hover:bg-green-700 dark:hover:bg-green-400',
  emerald: 'hover:bg-emerald-700 dark:hover:bg-emerald-400',
  teal: 'hover:bg-teal-700 dark:hover:bg-teal-400',
  cyan: 'hover:bg-cyan-700 dark:hover:bg-cyan-400',
  sky: 'hover:bg-sky-700 dark:hover:bg-sky-400',
  blue: 'hover:bg-blue-700 dark:hover:bg-blue-400',
  indigo: 'hover:bg-indigo-700 dark:hover:bg-indigo-400',
  violet: 'hover:bg-violet-700 dark:hover:bg-violet-400',
  purple: 'hover:bg-purple-700 dark:hover:bg-purple-400',
  fuchsia: 'hover:bg-fuchsia-700 dark:hover:bg-fuchsia-400',
  pink: 'hover:bg-pink-700 dark:hover:bg-pink-400',
  rose: 'hover:bg-rose-700 dark:hover:bg-rose-400',
  slate: 'hover:bg-slate-700 dark:hover:bg-slate-400',
  gray: 'hover:bg-gray-700 dark:hover:bg-gray-400',
  zinc: 'hover:bg-zinc-700 dark:hover:bg-zinc-400',
  neutral: 'hover:bg-neutral-700 dark:hover:bg-neutral-400',
  stone: 'hover:bg-stone-700 dark:hover:bg-stone-400',
  white: 'hover:bg-white dark:hover:bg-white',
  black: 'hover:bg-black dark:hover:bg-black',
} as Record<Colors, string>;


export const TailwindFocusVisibleOutlineColors = {
  red: 'focus-visible:outline-red-400',
  orange: 'focus-visible:outline-orange-400',
  amber: 'focus-visible:outline-amber-400',
  yellow: 'focus-visible:outline-yellow-400',
  lime: 'focus-visible:outline-lime-400',
  green: 'focus-visible:outline-green-400',
  emerald: 'focus-visible:outline-emerald-400',
  teal: 'focus-visible:outline-teal-400',
  cyan: 'focus-visible:outline-cyan-400',
  sky: 'focus-visible:outline-sky-400',
  blue: 'focus-visible:outline-blue-400',
  indigo: 'focus-visible:outline-indigo-400',
  violet: 'focus-visible:outline-violet-400',
  purple: 'focus-visible:outline-purple-400',
  fuchsia: 'focus-visible:outline-fuchsia-400',
  pink: 'focus-visible:outline-pink-400',
  rose: 'focus-visible:outline-rose-400',
  slate: 'focus-visible:outline-slate-400',
  gray: 'focus-visible:outline-gray-400',
  zinc: 'focus-visible:outline-zinc-400',
  neutral: 'focus-visible:outline-neutral-400',
  stone: 'focus-visible:outline-stone-400',
  black: 'focus-visible:outline-black',
  white: 'focus-visible:outline-white',
} as Record<Colors, string>;


export const TailwindGroupDataFocusTextColors200 = {
  red: 'group-data-focus:text-red-200 dark:group-data-focus:text-red-100',
  orange: 'group-data-focus:text-orange-200 dark:group-data-focus:text-orange-100',
  amber: 'group-data-focus:text-amber-200 dark:group-data-focus:text-amber-100',
  yellow: 'group-data-focus:text-yellow-200 dark:group-data-focus:text-yellow-100',
  lime: 'group-data-focus:text-lime-200 dark:group-data-focus:text-lime-100',
  green: 'group-data-focus:text-green-200 dark:group-data-focus:text-green-100',
  emerald: 'group-data-focus:text-emerald-200 dark:group-data-focus:text-emerald-100',
  teal: 'group-data-focus:text-teal-200 dark:group-data-focus:text-teal-100',
  cyan: 'group-data-focus:text-cyan-200 dark:group-data-focus:text-cyan-100',
  sky: 'group-data-focus:text-sky-200 dark:group-data-focus:text-sky-100',
  blue: 'group-data-focus:text-blue-200 dark:group-data-focus:text-blue-100',
  indigo: 'group-data-focus:text-indigo-200 dark:group-data-focus:text-indigo-100',
  violet: 'group-data-focus:text-violet-200 dark:group-data-focus:text-violet-100',
  purple: 'group-data-focus:text-purple-200 dark:group-data-focus:text-purple-100',
  fuchsia: 'group-data-focus:text-fuchsia-200 dark:group-data-focus:text-fuchsia-100',
  pink: 'group-data-focus:text-pink-200 dark:group-data-focus:text-pink-100',
  rose: 'group-data-focus:text-rose-200 dark:group-data-focus:text-rose-100',
  slate: 'group-data-focus:text-slate-200 dark:group-data-focus:text-slate-100',
  gray: 'group-data-focus:text-gray-200 dark:group-data-focus:text-gray-100',
  zinc: 'group-data-focus:text-zinc-200 dark:group-data-focus:text-zinc-100',
  neutral: 'group-data-focus:text-neutral-200 dark:group-data-focus:text-neutral-100',
  stone: 'group-data-focus:text-stone-200 dark:group-data-focus:text-stone-100',
  white: 'group-data-focus:text-white dark:group-data-focus:text-white',
  black: 'group-data-focus:text-black dark:group-data-focus:text-black',
} as Record<Colors, string>;

