Names:
  - company
  - recipe
  - todo
  - contact_info
  - experience
  - job
  - skill
  - project
  - entry
  - social
  - home
  - video
  - reference
  - archived
  - flagged
  - favorited
  - application
  - applied
  - scheduled
  - interviewed
  - passed
  - done
  - offered
  - negotiating
  - accepted