tags:
  - ruby
  - rails
  - js
  - resource
  - reference
  - forlater
  - html
  - css
  - scss
  - sql
  - stack
  - postgres
  - react
  - bootstrap
  - tailwind
  - tutorial
  - tool
  - testing
  - video
  - gem
  - documentation
  - docs
  - npm
  - mdn
  - fis
  - node
  - project
  - personal
  - work
  - dom
  - redux
  - thunk
  - practice
  - github
  - git
  - codecademy
  - self
  - guide
  - homebrew
  - bash
  - scamazon
  - writing
  - setup
  - shopping
  - regex
  - oauth
  - omniauth
  - bot
  - frontend
  - backend
  - database
  - db
  - faker
  - devise
  - java
  - typescript
  - ts
  - flagged
  - medium
  - social
  - favorite
  - standby
  - travel
  - contact
  - whilom


links: 
  - {name: "Google", href: "https://www.google.com", pinned: false}
  - {name: "Twitter", href: "https://www.twitter.com", pinned: false}
  - {name: "Wikipedia", href: "https://www.wikipedia.com", pinned: false}
