tags:
  - ruby
  - rails
  - js
  - education
  - resource
  - reference
  - forlater
  - html
  - css
  - scss
  - sql
  - stack
  - postgres
  - react
  - bootstrap
  - tailwind
  - tutorial
  - tool
  - testing
  - video
  - gem
  - documentation
  - docs
  - npm
  - mdn
  - fis
  - node
  - project
  - personal
  - work
  - dom
  - redux
  - thunk
  - practice
  - github
  - git
  - codecademy
  - jobhunt
  - self
  - guide
  - homebrew
  - bash
  - scamazon
  - writing
  - pt
  - setup
  - shopping
  - wishlist
  - regex
  - oauth
  - omniauth
  - bot
  - frontend
  - backend
  - database
  - db
  - faker
  - devise
  - java
  - typescript
  - ts
  - wikiverse
  - ba
  - flagged
  - low
  - med
  - medium
  - high
  - social
  - wanttotry
  - favorite
  - standby
  - travel
  - contact
  - whilom
  - lacey
  - keto
  - vegetarian
  - ferment
  - dehydrate
  - filling
  - light
  - desert
  - main
  - breakfast
  - side
  - vegetable
  - healthy
  - pasta
  - steak
  - chicken
  - drink
  - grandma
  - mom
  - oldman
  - italian
  - asian
  - mexican
  - spanish
  - fresh
  - fish
  - warm
  - soup
  - salad
  - appetizer
  - condiment
  - staple
  - dateidea
  - bored
contexts:
  - company
  - recipe
  - todo
  - contact_info
  - experience
  - job
  - skill
  - project
  - entry
  - social
  - home
  - video
  - reference
  - archived
  - flagged
  - favorited
  - application
  - applied
  - scheduled
  - interviewed
  - passed
  - offered
  - negotiating
  - accepted
  - done
links:
  - {name: "Google", href: "https://www.google.com", icon: "test", pinned: false }
  - {name: "Sick Apron", href: "https://www.hedleyandbennett.com/products/the-big-apron-denver", icon: "covered", pinned: false }
  - {name: "Where is Webb?", href: "https://www.gstatic.com/og/_/ss/k=og.qtm.HxoUAioIAQQ.L.W.O/m=qcwid/excm=qaaw,qadd,qaid,qein,qhaw,qhbr,qhch,qhga,qhid,qhin,qhpr/d=1/ed=1/ct=zgms/rs=AA2YrTvrQeu0vR2dT9ScDnl4fHY3p_tRGg", icon: "thebigpicture", pinned: false }