tags:
  - ruby
  - rails
  - js
  - resources
  - references
  - forlater
  - html
  - css
  - scss
  - sql
  - stack
  - postgres
  - react
  - bootstrap
  - tailwind
  - tutorial
  - tools
  - testing
  - video
  - gem
  - documentation
  - docs
  - npm
  - mdn
  - fis
  - node
  - project
  - personal
  - work
  - dom
  - redux
  - thunk
  - practice
  - github
  - git
  - codecademy
  - self
  - guide
  - homebrew
  - bash
  - shell
  - zshell
  - zsh
  - scamazon
  - writing
  - setup
  - shopping
  - regex
  - oauth
  - omniauth
  - bot
  - frontend
  - backend
  - database
  - db
  - java
  - typescript
  - ts
  - flagged
  - auth
  - social
  - ref
  - javascript

links:
  - { name: 'Twitter', href: 'https://www.twitter.com', pinned: false, tagNames: ['tools', 'social'] }
  - {
      name: 'Wikipedia',
      href: 'https://www.wikipedia.com',
      pinned: true,
      tagNames: ['resources', 'references', 'tools'],
    }
  - {
      name: 'Rails Docs',
      href: 'https://guides.rubyonrails.org/',
      pinned: false,
      tagNames: ['ruby', 'rails', 'references', 'docs', 'documentation', 'setup', 'flagged', 'ref'],
    }
  - {
      name: 'Stackoverflow',
      href: 'https://stackoverflow.com/',
      pinned: true,
      tagNames: ['docs', 'references', 'ref', 'resources', 'stack'],
    }
  - {
      name: 'GitHub',
      href: 'https://agithub.com/',
      pinned: true,
      tagNames: ['docs', 'references', 'ref', 'resources', 'stack', 'work', 'tools', 'git', 'github'],
    }
  - {
      name: 'Faker',
      href: 'https://github.com/faker-ruby/faker',
      pinned: false,
      tagNames:
        [
          'ruby',
          'rails',
          'references',
          'docs',
          'documentation',
          'setup',
          'ref',
          'db',
          'database',
          'testing',
          'gem',
          'setup',
          'sql',
          'postgres',
        ],
    }
  - {
      name: 'Devise',
      href: 'https://github.com/heartcombo/devise',
      pinned: false,
      tagNames:
        [
          'ruby',
          'rails',
          'references',
          'docs',
          'documentation',
          'ref',
          'gem',
          'auth',
          'oauth',
          'omniauth',
          'setup',
          'resources',
        ],
    }
  - {
      name: 'MDN Mozilla Docs',
      href: 'https://github.com/heartcombo/devise',
      pinned: false,
      tagNames:
        [
          'references',
          'docs',
          'documentation',
          'flagged',
          'ref',
          'setup',
          'resources',
          'js',
          'javascript',
          'frontend',
          'mdn',
        ],
    }
  - {
      name: 'React Docs',
      href: 'https://github.com/heartcombo/devise',
      pinned: false,
      tagNames:
        [
          'references',
          'docs',
          'documentation',
          'flagged',
          'ref',
          'setup',
          'resources',
          'js',
          'javascript',
          'frontend',
          'mdn',
          'react',
          'ts',
          'typescript',
        ],
    }
