Names:
  - ruby
  - rails
  - js
  - education
  - resource
  - reference
  - forlater
  - html
  - css
  - java
  - sql
  - stack
  - postgres
  - react
  - bootstrap
  - tailwind
  - tutorial
  - tool
  - testing
  - video
  - gem
  - documentation
  - docs
  - npm
  - mdn
  - fis
  - node
  - project
  - personal
  - work
  - dom
  - redux
  - thunk
  - practice
  - github
  - git
  - guide
  - homebrew
  - bash
  - scamazon
  - writing
  - pt
  - setup
  - shopping
  - wishlist
  - regex
  - oauth
  - omniauth
  - bot
  - frontend
  - backend
  - database
  - db
  - faker
  - devise
  - java
  - typescript
  - ts
  - wikiverse
  - ba
  - flagged
  - low
  - med
  - medium
  - high
  - social
  - wanttotry
  - favorite
  - standby
  - travel
  - contact
  - whilom
  - lacey
  - keto
  - vegetarian
  - ferment
  - dehydrate
  - filling
  - light
  - desert
  - main
  - breakfast
  - side
  - vegetable
  - healthy
  - pasta
  - steak
  - chicken
  - drink
  - grandma
  - mom
  - oldman
  - italian
  - asian
  - mexican
  - spanish
  - fresh
  - fish
  - warm
  - soup
  - salad
  - appetizer
  - condiment
  - staple
  - 